model_name: "facebook/wav2vec2-base-960h"

opt: AdamW
lr: 0.0001
scheduler: linear

# train_all: False
train_transformer: True
# train_feature: True
# train_LN: True
# bias_only: False

train_config:
  num_train_epochs: 10
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  grad_clip_thresh: 1.0
  weight_decay: 0.0

  save_strategy: "epoch"
  logging_steps: 100
